# Generated by Django 6.0.2 on 2026-09-04 04:46

import found_items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Found', 'Found'), ('Not Found', 'Not Found')], max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date_found', models.DateField()),
                ('location_found', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=found_items.models.Report_Directory_Name)),
            ],
        ),
    ]
