# Generated by Django 6.0.2 on 2026-09-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportLostItem',
            new_name='ReportFoundItem',
        ),
    ]
