# Generated by Django 6.0.2 on 2026-09-12 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0003_reportfounditem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfounditem',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='found_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
